name: release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    uses: EcommerceDevops/workflows/.github/workflows/release.yml@main
    secrets: inherit
