# .github/workflows/security-scan.yml

name: "🛡️ Security Scan with Trivy"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-scan:
    permissions:
      contents: read
      security-events: write
    uses: EcommerceDevops/workflows/.github/workflows/trivy.yml@main
    secrets: inherit
